<!-- Footer Start-->
<div id="footer">
  <a href="http://validator.w3.org/check?uri=referer">
    <img src="images/valid-xhtml.png" alt="Valid XHTML 1.0" />
  </a> | <a href="http://jigsaw.w3.org/css-validator/check/referer">
    <img src="images/valid-css2.png" alt="Valid CSS2" />
  </a> | (C) YAPS Team 2006-2007 | <a href="/rss/recorded.xml" title="List of complete recordings">
    <img src="images/rss_feed_icon.png" alt="RSS-Feed"></img>
  </a> | page rendered in %page_render_time%; build %build_version%
</div>
<!-- Footer Ende -->